"""create health_checks

Revision ID: cfe4d471a7d1
Revises: 
Create Date: 2025-09-18 00:57:05.243189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cfe4d471a7d1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_checks',
    sa.Column('check_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('check_datetime', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("TIMEZONE('UTC',NOW())"), nullable=False),
    sa.PrimaryKeyConstraint('check_id')
    )
    op.create_index('ix_health_checks_check_datetime', 'health_checks', ['check_datetime'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_health_checks_check_datetime', table_name='health_checks')
    op.drop_table('health_checks')
    # ### end Alembic commands ###
